// apps/front/src/pages/client/layout/footer/index.tsx
import { Link } from 'react-router-dom';

import { Routes } from '../../../../router/routes/routes';

export function Footer() {
  return (
    <footer className="footer footer-5">
      <div className="footer-top">
        <div className="container">
          <div className="row">
            <div className="col-lg-4">
              <div className="footer-widget">
                <div className="footer-logo">
                  <Link to={Routes.home}>
                    <img src="/logo.svg" alt="logo" />
                  </Link>
                </div>
                <div className="footer-content">
                  <div>
                    <p className="fs-16">
                      <span className="ti ti-device-mobile me-2"></span>123 -
                      456 - 789
                    </p>
                  </div>
                  <div>
                    <p className="fs-16">
                      <span className="ti ti-mail me-2"></span>
                      hello&#64;prosonwork.com
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-lg-4">
              <div className="footer-widget">
                <h2 className="footer-title">Restez en contact avec nous</h2>
                <div className="social-icon">
                  <ul className="mb-0">
                    <li>
                      <a href="#">
                        <i className="ti ti-brand-facebook"></i>{' '}
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i className="ti ti-brand-instagram"></i>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i className="ti ti-brand-linkedin"></i>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div className="col-lg-4">
              <div className="footer-widget">
                <h2 className="footer-subtitle">Inscription à la newsletter</h2>
                <div className="subscribe-form mb-4">
                  <input
                    type="email"
                    className="form-control"
                    placeholder="Enter Email Address"
                  />
                  <button
                    type="submit"
                    className="btn footer-btn btn-dark d-flex justify-content-center align-items-center"
                  >
                    <i className="feather icon-send"></i>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}

// Front/src/app/client/common/footer/footer.component.ts
import { Component } from '@angular/core';
import { routes } from 'src/app/shared/routes/routes';

@Component({
  selector: 'app-client-footer',
  templateUrl: './footer.component.html',
})
export class FooterComponent {
  public routes = routes
}

<footer class="footer footer-5">
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="footer-widget">
                        <div class="footer-logo">
                            <a [routerLink]="routes.home"><img src="assets/logo/logo.svg" alt="logo"></a>
                        </div>
                        <div class="footer-content">
                            <div>
                                <p class="fs-16"><span class="ti ti-device-mobile me-2"></span>123 - 456 - 789</p>
                            </div>
                            <div>
                                <p class="fs-16"><span class="ti ti-mail me-2"></span>hello&#64;prosonwork.com</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="footer-widget">
                        <h2 class="footer-title">Restez en contact avec nous</h2>
                        <div class="social-icon">
                            <ul class="mb-0">
                                <li>
                                    <a href="javascript:void(0);"><i class="ti ti-brand-facebook"></i> </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);"><i class="ti ti-brand-instagram"></i></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);"><i class="ti ti-brand-linkedin"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="footer-widget">
                        <h2 class="footer-subtitle">Inscription à la newsletter</h2>
                        <div class="subscribe-form mb-4">
                            <input type="email" class="form-control" placeholder="Enter Email Address">
                            <button type="submit" class="btn footer-btn btn-dark d-flex justify-content-center align-items-center">
                                <i class="feather icon-send"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
