// Front/src/app/shared/not-found/error404.component.ts
import { Component } from '@angular/core';
import { routes } from 'src/app/shared/routes/routes';

@Component({
  selector: 'app-error404',
  templateUrl: './error404.component.html',
})
export class Error404Component {
  public routes = routes;
}

<div
  class="d-flex justify-content-center vh-100 overflow-auto flex-column error-404"
>
  <div class="contacts-overlay-img d-none d-md-block">
    <img src="assets/img/bg/bg-07.png" alt="img" class="img-fluid" />
  </div>
  <!-- Header -->
  <div class="authentication-header">
    <div class="container">
      <div class="col-md-12">
        <div class="text-center">
          <img class="w-25 h-25" src="assets/logo/logo.svg" alt="logo" />
        </div>
      </div>
    </div>
  </div>
  <!-- /Header -->

  <!-- Main Wrapper -->
  <div class="main-wrapper">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6 mx-auto">
          <div class="img-success d-flex justify-content-center mx-auto">
            <img
              src="assets/img/bg/error-404.png"
              alt="Img"
              class="img-fluid"
            />
          </div>
          <div>
            <h1 class="text-center display-6 mb-2">404 Oups ! Page non trouvée</h1>
            <div class="text-center mb-4">
              <span class="text-gray fs-14"
                >Cette page n'existe pas ou a été supprimée ! Nous vous invitons à revenir à
                l'accueil.</span
              >
            </div>
            <div class="d-flex justify-content-center">
              <a
                [routerLink]="routes.home"
                class="btn btn-dark d-flex align-items-center"
                ><i class="ti ti-circle-arrow-left me-1"></i>Retour à l'accueil</a
              >
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /Main Wrapper -->
</div>

// apps/front/src/feature-module/frontend/pages/Error page/error404.tsx
import React from 'react';
import { Link } from 'react-router-dom';

import { all_routes } from '../../../../core/data/routes/all_routes';
import ImageWithBasePath from '../../../../core/img/ImageWithBasePath';
import PagesAuthHeader from '../authentication/common/header';
const Error404 = () => {
  const routes = all_routes;
  return (
    <>
      <div className="error-404">
        <div className="contacts-overlay-img d-none d-md-block">
          <ImageWithBasePath src="assets/img/bg/bg-07.png" alt="img" className="img-fluid" />
        </div>
        {/* Header */}
        <PagesAuthHeader/>
        {/* /Header */}
        {/* Main Wrapper */}
        <div className="main-wrapper">
          <div className="container">
            <div className="row justify-content-center">
              <div className="col-md-6 mx-auto">
                <div className="img-success d-flex justify-content-center mx-auto">
                  <ImageWithBasePath
                    src="assets/img/bg/error-404.png"
                    alt="Img"
                    className="img-fluid"
                  />
                </div>
                <div>
                  <h1 className="text-center display-6 mb-2">
                    404 Oops! Page Not Found
                  </h1>
                  <div className="text-center mb-4">
                    <span className="text-gray fs-14 ">
                      This page doesn&apos;t exist or was removed! We suggest you
                      back to home.
                    </span>
                  </div>
                  <div className="d-flex justify-content-center">
                    <Link
                      to={routes.index}
                      className="btn btn-dark d-flex align-items-center "
                    >
                      <i className="ti ti-circle-arrow-left me-1" />
                      Back to Home
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* /Main Wrapper */}
      </div>
    </>
  );
};

export default Error404;
