// Front/src/app/shared/geo-location/geo-location.component.ts
import { Component, AfterViewInit, Input } from '@angular/core';
import * as L from 'leaflet';
import { GeoLocationService } from './geo-location.service';
import { GeoLocation } from '../models/model';
import { first } from 'rxjs';

@Component({
  selector: 'app-geo-location',
  templateUrl: './geo-location.component.html',
  styleUrl: './geo-location.component.css',
})
export class GeoLocationComponent implements AfterViewInit {
  private map: L.Map | null = null;
  private marker: L.Marker | null = null;
  @Input() parentControl: boolean = false;

  constructor(private geoLocationService: GeoLocationService) {}

  ngAfterViewInit(): void {
    if (!this.parentControl) {
      this.initMap();
    }
  }

  initMap(): void {
    const tiles = L.tileLayer(
      'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
      {
        maxZoom: 18,
        minZoom: 3,
        attribution:
          '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',
      }
    );

    this.map = L.map('map', {
      center: [
        34.551811369170494, 10.546875000000002],
      zoom: 3,
    });

    tiles.addTo(this.map);

    this.map.addEventListener('click', (e) => this.onClick(e));

    this.geoLocationService.selectedLocation$.subscribe((value) => {
      if (value) {
        this.setMarker(value);
      }
    });
  }

  onClick(event: L.LeafletMouseEvent) {
    console.log(event.latlng)
    const location = {
      latitude: event.latlng.lat,
      longitude: event.latlng.lng,
    };
    this.geoLocationService.setGeoLocation(location);
  }

  setMarker(geoLocation: GeoLocation) {
    if (this.map && this.marker) {
      this.map.removeLayer(this.marker);
    }

    this.marker = new L.Marker({
      lat: geoLocation.latitude,
      lng: geoLocation.longitude,
    });

    this.map?.addLayer(this.marker);

    this.map!.flyTo([geoLocation.latitude, geoLocation.longitude], 15);
  }

  resizeMap() {
    this.map?.invalidateSize();
  }

  handleCurrentLocation() {
    navigator.geolocation.getCurrentPosition((position) => {
      this.geoLocationService.setGeoLocation(position.coords);
      this.setMarker(position.coords);
    });
  }
}

<div class="map-container">
  <div id="map"></div>
</div>

<div class="d-flex align-items-center justify-content-center">
  <div class="btn btn-primary" (click)="handleCurrentLocation()">Utiliser la localisation actuelle</div>
</div>

// apps/front/src/components/GeoLocation/index.tsx
import * as L from 'leaflet';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Modal } from 'react-bootstrap';

import { Address } from '../../core/Interface/interface';
import { useConnectedUser } from '../../hooks/useAuth';
import {
  getGeolocationText,
  stringToAddress,
} from '../../utils/getGeolocationText';

import 'leaflet/dist/leaflet.css';

interface GeoLocationProps {
  show: boolean;
  onHide: () => void;
  handleSave?: (
    geoLocation: Address | null,
    text: string,
  ) => any | Promise<any>;
  geoLocation?: Address | null;
}

export function GeoLocationMap(
  { onHide, show, handleSave, geoLocation }: GeoLocationProps = {
    onHide: () => {},
    show: false,
    handleSave: (geoLocation: Address | null, text: string) => {},
    geoLocation: null,
  },
) {
  const { data: user } = useConnectedUser();
  const containerRef = useRef<HTMLDivElement | null>(null);
  const mapRef = useRef<L.Map | null>(null);
  const markerRef = useRef<L.Marker | null>(null);
  const [text, setText] = useState('');
  const [geoLoc, setGeoLoc] = useState<Address | null>(
    geoLocation ?? (user?.address ? stringToAddress(user?.address!) : null),
  );

  const setMarkerOnMap = useCallback(() => {
    if (mapRef.current && geoLoc) {
      if (markerRef.current) {
        mapRef.current.removeLayer(markerRef.current);
        markerRef.current = null;
      }

      markerRef.current = L.marker([geoLoc.latitude, geoLoc.longitude]);
      markerRef.current.addTo(mapRef.current);
      mapRef.current.flyTo([geoLoc.latitude, geoLoc.longitude], 15);

      getGeolocationText(geoLoc).then(setText);
    }
  }, [geoLoc, mapRef.current, setText]);

  useEffect(() => {
    setMarkerOnMap();
  }, [setMarkerOnMap, geoLoc]);

  const init = useCallback(() => {
    if (containerRef.current) {
      mapRef.current = L.map(containerRef.current).setView(
        [34.30333389334934, 9.514391023206112],
        6,
      );

      L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 18,
        minZoom: 3,
      }).addTo(mapRef.current);

      mapRef.current.on('click', (e) =>
        setGeoLoc({
          latitude: e.latlng.lat,
          longitude: e.latlng.lng,
        }),
      );

      setTimeout(() => mapRef.current?.invalidateSize(), 500);

      if (geoLoc) {
        setMarkerOnMap();
      }
    }
  }, [containerRef.current, mapRef.current, setMarkerOnMap]);

  const handleCurrentLocation = useCallback(() => {
    navigator.geolocation.getCurrentPosition((position) =>
      setGeoLoc(position.coords),
    );
  }, [setGeoLoc]);

  const hide = useCallback(() => {
    markerRef.current?.off();
    markerRef.current?.remove();
    markerRef.current = null;

    mapRef.current?.off();
    mapRef.current?.remove();
    mapRef.current = null;

    onHide();
  }, [onHide, mapRef.current, markerRef.current, geoLoc, text]);

  useEffect(() => {
    if (geoLoc) {
      (async function () {
        await handleSave?.(geoLoc, text);
      })();
    }
  }, [geoLoc, text]);

  return (
    <Modal show={show} onHide={hide} size="xl" centered onEntered={init}>
      <Modal.Body>
        <div
          className="position-relative overflow-hidden m-3 border border-2 border-dark"
          style={{ height: '400px' }}
        >
          <div className="h-100 w-100" ref={containerRef}></div>
        </div>
        <span>{text}</span>

        <div className="d-flex align-items-center justify-content-center">
          <div className="btn btn-primary" onClick={handleCurrentLocation}>
            Utiliser la localisation actuelle
          </div>
        </div>
      </Modal.Body>
    </Modal>
  );
}
