// Front/src/app/client/categories/categories.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Category } from 'src/app/shared/models/model';
import { routes } from 'src/app/shared/routes/routes';
import { CategoriesService } from 'src/app/shared/services/categories.service';

@Component({
  selector: 'app-categories',
  templateUrl: './categories.component.html',
})
export class CategoriesComponent implements OnInit {
  public routes = routes;
  public categories: Category[] = [];

  constructor(
    private categoriesService: CategoriesService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.categoriesService.categories$.subscribe(
      (data) => (this.categories = data)
    );
  }

  goToSearch() {
    this.router.navigateByUrl(this.routes.services);
  }
}

<div class="page-wrapper">
  <div class="content">
    <div class="container">
      <div class="row justify-content-center align-items-center">
        @for (category of categories; track category.id) {
        <div class="col-lg-3 col-md-6" (click)="goToSearch()">
          <div class="category card wow fadeInUp" data-wow-delay="0.3s">
            <div class="card-body">
              <div
                class="feature-icon d-flex justify-content-center align-items-center mb-2"
              >
                <span
                  class="rounded-pill d-flex justify-content-center align-items-center p-3"
                >
                  <img [src]="category.logo" class="img-fluid" alt="logo" />
                </span>
              </div>
              <h5 class="text-center">{{ category.name }}</h5>
              <div class="overlay">
                <img [src]="category.img" class="img-fluid" alt="img" />
              </div>
            </div>
          </div>
        </div>
        }
      </div>
    </div>
  </div>
</div>

// apps/front/src/pages/client/Categories/index.tsx
import { Link } from 'react-router-dom';

import { useCategories } from '../../../hooks/useCategory';
import { Routes } from '../../../router/routes/routes';

export function Categories() {
  const { data: categories } = useCategories();

  if (!categories?.items) {
    return <></>;
  }

  return (
    <div className="page-wrapper">
      <div className="content">
        <div className="container">
          <div className="row justify-content-center align-items-center">
            {categories.items.map((category) => (
              <div key={category.id} className="col-lg-3 col-md-6">
                <Link to={`${Routes.search}?categories=${category.id}`}>
                  <div
                    className="category card wow fadeInUp"
                    data-wow-delay="0.3s"
                  >
                    <div className="card-body">
                      <div className="feature-icon d-flex justify-content-center align-items-center mb-2">
                        <span className="rounded-pill d-flex justify-content-center align-items-center p-3">
                          <img
                            src={category.icon?.filePath}
                            className="img-fluid"
                            alt="logo"
                          />
                        </span>
                      </div>
                      <h5 className="text-center">{category.name}</h5>
                      <div className="overlay">
                        <img
                          src={category.image?.filePath}
                          className="img-fluid"
                          alt="img"
                        />
                      </div>
                    </div>
                  </div>
                </Link>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
