// apps/front/src/pages/client/layout/header/index.tsx
import { Link } from 'react-router-dom';

import { useConnectedUser, useLogout } from '../../../../hooks/useAuth';
import { Routes } from '../../../../router/routes/routes';

export function Header() {
  const { data: user } = useConnectedUser();
  const { mutate: logout } = useLogout();

  return (
    <header className="header">
      <div className="container">
        <nav className="navbar navbar-expand-lg header-nav">
          <div className="navbar-header">
            <Link to={Routes.home} className="navbar-brand logo">
              <img src="/logo.svg" alt="logo" className="img-fluid" />
            </Link>
            <Link to={Routes.home} className="navbar-brand logo-small">
              <img src="/logo.svg" alt="logo" className="img-fluid" />
            </Link>
          </div>
          <div className="main-menu-wrapper">
            <div className="menu-header">
              <Link to={Routes.home} className="menu-logo">
                <img src="/logo.svg" alt="logo" className="img-fluid" />
              </Link>
            </div>
          </div>
          {user ? (
            <>
              <div className="header-btn d-flex align-items-center">
                <div className="provider-head-links">
                  <a
                    href="#"
                    className="d-flex align-items-center justify-content-center me-2 notify-link"
                    data-bs-toggle="dropdown"
                  >
                    <i className="feather icon-bell"></i>
                  </a>
                  <div className="dropdown-menu dropdown-menu-end notification-dropdown p-4">
                    <div className="d-flex dropdown-body align-items-center justify-content-between border-bottom p-0 pb-3 mb-3">
                      <h6 className="notification-title">
                        Notifications
                        <span className="fs-18 text-gray"> (2)</span>
                      </h6>
                      <div className="d-flex align-items-center">
                        <a href="#" className="text-primary fs-15 me-3 lh-1">
                          Mark all as read
                        </a>
                        <div className="dropdown">
                          <a
                            href="#"
                            className="bg-white dropdown-toggle"
                            data-bs-toggle="dropdown"
                            data-bs-auto-close="outside"
                          >
                            <i className="ti ti-calendar-due me-1"></i>Today
                          </a>
                          <ul className="dropdown-menu mt-2 p-3">
                            <li>
                              <a href="#" className="dropdown-item rounded-1">
                                This Week
                              </a>
                            </li>
                            <li>
                              <a href="#" className="dropdown-item rounded-1">
                                Last Week
                              </a>
                            </li>
                            <li>
                              <a href="#" className="dropdown-item rounded-1">
                                Last Week
                              </a>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                    <div className="noti-content">
                      <div className="d-flex flex-column">
                        <div className="border-bottom mb-3 pb-3">
                          <a>
                            <div className="d-flex">
                              <span className="avatar avatar-lg me-2 flex-shrink-0">
                                <img
                                  src="assets/img/profiles/avatar-52.jpg"
                                  alt="Profile"
                                  className="rounded-circle"
                                />
                              </span>
                              <div className="flex-grow-1">
                                <div className="d-flex align-items-center">
                                  <p className="mb-1 w-100">
                                    <span className="text-dark fw-semibold">
                                      Stephan Peralt
                                    </span>
                                    rescheduled the service to 14/01/2024.
                                  </p>
                                  <span className="d-flex justify-content-end ">
                                    <i className="ti ti-point-filled text-primary"></i>
                                  </span>
                                </div>
                                <span>Just Now</span>
                              </div>
                            </div>
                          </a>
                        </div>
                        <div className="border-bottom mb-3 pb-3">
                          <a className="pb-0">
                            <div className="d-flex">
                              <span className="avatar avatar-lg me-2 flex-shrink-0">
                                <img
                                  src="assets/img/profiles/avatar-36.jpg"
                                  alt="Profile"
                                  className="rounded-circle"
                                />
                              </span>
                              <div className="flex-grow-1">
                                <div className="d-flex align-items-center">
                                  <p className="mb-1 w-100">
                                    <span className="text-dark fw-semibold">
                                      Harvey Smith
                                    </span>
                                    has requested your service.
                                  </p>
                                  <span className="d-flex justify-content-end ">
                                    <i className="ti ti-point-filled text-primary"></i>
                                  </span>
                                </div>
                                <span>5 mins ago</span>
                                <div className="d-flex justify-content-start align-items-center mt-2">
                                  <span className="btn btn-light btn-sm me-2">
                                    Deny
                                  </span>
                                  <span className="btn btn-dark btn-sm">
                                    Accept
                                  </span>
                                </div>
                              </div>
                            </div>
                          </a>
                        </div>
                        <div className="border-bottom mb-3 pb-3">
                          <a>
                            <div className="d-flex">
                              <span className="avatar avatar-lg me-2 flex-shrink-0">
                                <img
                                  src="assets/img/profiles/avatar-02.jpg"
                                  alt="Profile"
                                  className="rounded-circle"
                                />
                              </span>
                              <div className="flex-grow-1">
                                <p className="mb-1">
                                  <span className="text-dark fw-semibold">
                                    Anthony Lewis
                                  </span>
                                  has left feedback for your recent service
                                </p>
                                <span>10 mins ago</span>
                              </div>
                            </div>
                          </a>
                        </div>
                        <div className="border-0 mb-3 pb-0">
                          <a>
                            <div className="d-flex">
                              <span className="avatar avatar-lg me-2 flex-shrink-0">
                                <img
                                  src="assets/img/profiles/avatar-22.jpg"
                                  alt="Profile"
                                  className="rounded-circle"
                                />
                              </span>
                              <div className="flex-grow-1">
                                <p className="mb-1">
                                  <span className="text-dark fw-semibold">
                                    Brian Villaloboshas
                                  </span>
                                  cancelled the service scheduled for
                                  14/01/2024.
                                </p>
                                <span>15 mins ago</span>
                              </div>
                            </div>
                          </a>
                        </div>
                      </div>
                    </div>
                    <div className="d-flex p-0 notification-footer-btn">
                      <a href="#" className="btn btn-light rounded  me-2">
                        Cancel
                      </a>
                      <a href="#" className="btn btn-dark rounded ">
                        View All
                      </a>
                    </div>
                  </div>
                </div>
                <div className="provider-head-links">
                  <a className="d-flex align-items-center justify-content-center me-2">
                    <i className="feather icon-mail"></i>
                  </a>
                </div>
                <div className="dropdown">
                  <a
                    href="#"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                    className=""
                  >
                    <div className="booking-user d-flex align-items-center">
                      <span className="user-img">
                        <img
                          src="assets/img/profiles/avatar-02.jpg"
                          alt="user"
                        />
                      </span>
                    </div>
                  </a>
                  <ul className="dropdown-menu p-2">
                    <li>
                      <a
                        className="dropdown-item d-flex align-items-center"
                        href="#"
                        onClick={() => logout()}
                      >
                        <i className="ti ti-logout me-1"></i>Logout
                      </a>
                    </li>
                  </ul>
                </div>
                <div className="header__hamburger d-lg-none my-auto">
                  <div className="sidebar-menu">
                    <i className="fa-solid fa-bars"></i>
                  </div>
                </div>
              </div>
            </>
          ) : (
            <ul className="nav header-navbar-rht">
              <li className="nav-item">
                <Link to={Routes.register} className="nav-link header-reg">
                  Créer un compte
                </Link>
              </li>
              <li className="nav-item">
                <Link to={Routes.login} className="nav-link header-login">
                  <i className="fa-regular fa-circle-user me-2"></i>Se connecter
                </Link>
              </li>
            </ul>
          )}
        </nav>
      </div>
    </header>
  );
}

// Front/src/app/client/common/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { NavigationEnd, Router, Scroll } from '@angular/router';
import { User } from 'src/app/shared/models/model';
import { routes } from 'src/app/shared/routes/routes';
import { SidebarService } from 'src/app/shared/side-bar/pages-sidebar.service';

@Component({
  selector: 'app-client-header',
  templateUrl: './header.component.html',
})
export class HeaderComponent implements OnInit {
  public routes = routes;
  public connectedUser: User | null = null;

  constructor(private sidebarService: SidebarService, private router: Router) {}

  ngOnInit(): void {
    const check = (url: string) => {
      if (url.includes('dashboard')) {
        this.connectedUser = {};
      } else {
        this.connectedUser = null;
      }
    };

    this.router.events.subscribe((x) => {
      if (x instanceof NavigationEnd) {
        check(x.url);
      } else if (x instanceof Scroll) {
        check(x.routerEvent.url);
      }
    });
  }

  public toggleSidebar(): void {
    this.sidebarService.openSidebar();
  }
  public hideSidebar(): void {
    this.sidebarService.closeSidebar();
  }
}

<header class="header">
  <div class="container">
    <nav class="navbar navbar-expand-lg header-nav">
      <div class="navbar-header">
        <a (click)="toggleSidebar()"  id="mobile_btn" href="javascript:void(0);">
          <span class="bar-icon">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </a>
        <a [routerLink]="routes.home" class="navbar-brand logo">
          <img src="assets/logo/logo.svg" class="img-fluid" alt="Logo" />
        </a>
        <a [routerLink]="routes.home" class="navbar-brand logo-small">
          <img src="assets/logo/logo.svg" class="img-fluid" alt="Logo" />
        </a>
      </div>
      <div class="main-menu-wrapper">
        <div class="menu-header">
          <a [routerLink]="routes.home" class="menu-logo">
            <img src="assets/logo/logo.svg" class="img-fluid" alt="Logo" />
          </a>
          <a (click)="hideSidebar()" id="menu_close" class="menu-close" href="javascript:void(0);">
            <i class="fas fa-times"></i
          ></a>
        </div>
        <ul class="main-nav">
          <li class="login-link">
            <a [routerLink]="routes.Register">Register</a>
          </li>
          <li class="login-link">
            <a [routerLink]="routes.login">Login</a>
          </li>
        </ul>
      </div>
      @if (!connectedUser) {
        <ul class="nav header-navbar-rht">
          <li class="nav-item">
            <a class="nav-link header-reg" [routerLink]="routes.Register"
              >Register</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link header-login" [routerLink]="routes.login"
              ><i class="fa-regular fa-circle-user me-2"></i>Login</a
            >
          </li>
        </ul>
      } @else {
        <div class="header-btn d-flex align-items-center">
          <div class="provider-head-links">
            <a href="javascript:void(0);" class="d-flex align-items-center justify-content-center me-2 notify-link" data-bs-toggle="dropdown"><i class="feather icon-bell"></i></a>
            <div class="dropdown-menu dropdown-menu-end notification-dropdown p-4">
              <div class="d-flex dropdown-body align-items-center justify-content-between border-bottom p-0 pb-3 mb-3">
                <h6 class="notification-title">Notifications <span class="fs-18 text-gray"> (2)</span></h6>
                <div class="d-flex align-items-center">
                  <a href="#" class="text-primary fs-15 me-3 lh-1">Mark all as read</a>
                  <div class="dropdown">
                    <a href="javascript:void(0);" class="bg-white dropdown-toggle"
                      data-bs-toggle="dropdown" data-bs-auto-close="outside"><i class="ti ti-calendar-due me-1"></i>Today
                    </a>
                    <ul class="dropdown-menu mt-2 p-3">
                      <li>
                        <a href="javascript:void(0);" class="dropdown-item rounded-1">
                          This Week
                        </a>
                      </li>
                      <li>
                        <a href="javascript:void(0);" class="dropdown-item rounded-1">
                          Last Week
                        </a>
                      </li>
                      <li>
                        <a href="javascript:void(0);" class="dropdown-item rounded-1">
                          Last Week
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
  
              <div class="noti-content">
                <div class="d-flex flex-column">
                  <div class="border-bottom mb-3 pb-3">
                    <a [routerLink]="routes.notification">
                      <div class="d-flex">
                        <span class="avatar avatar-lg me-2 flex-shrink-0">
                          <img src="assets/img/profiles/avatar-52.jpg" alt="Profile" class="rounded-circle">
                        </span>
                        <div class="flex-grow-1">
                          <div class="d-flex align-items-center">
                          <p class="mb-1 w-100"><span class="text-dark fw-semibold">Stephan Peralt</span> rescheduled the service to 14/01/2024. </p>
                          <span class="d-flex justify-content-end "> <i class="ti ti-point-filled text-primary"></i></span>
                          </div> 
                          <span>Just Now</span>
                        </div>
                      </div>
                    </a>
                  </div>
                  <div class="border-bottom mb-3 pb-3">
                    <a [routerLink]="routes.notification" class="pb-0">
                      <div class="d-flex">
                        <span class="avatar avatar-lg me-2 flex-shrink-0">
                          <img src="assets/img/profiles/avatar-36.jpg" alt="Profile" class="rounded-circle">
                        </span>
                        <div class="flex-grow-1">
                          <div class="d-flex align-items-center">
                            <p class="mb-1 w-100"><span class="text-dark fw-semibold">Harvey Smith</span> has requested your service.</p>
                            <span class="d-flex justify-content-end "> <i class="ti ti-point-filled text-primary"></i></span>
                          </div>
                          <span>5 mins ago</span>
                          <div class="d-flex justify-content-start align-items-center mt-2">
                            <span class="btn btn-light btn-sm me-2">Deny</span>
                            <span class="btn btn-dark btn-sm">Accept</span>
                          </div>
                        </div>
                      </div>
                    </a>					
                  </div>
                  <div class="border-bottom mb-3 pb-3">
                    <a [routerLink]="routes.notification">
                      <div class="d-flex">
                        <span class="avatar avatar-lg me-2 flex-shrink-0">
                          <img src="assets/img/profiles/avatar-02.jpg" alt="Profile" class="rounded-circle">
                        </span>
                        <div class="flex-grow-1">
                          <p class="mb-1"><span class="text-dark fw-semibold"> Anthony Lewis</span> has left feedback for your recent service </p>
                          <span>10 mins ago</span>
                        </div>
                      </div>
                    </a>
                  </div>
                  <div class="border-0 mb-3 pb-0">
                    <a [routerLink]="routes.notification">
                      <div class="d-flex">
                        <span class="avatar avatar-lg me-2 flex-shrink-0">
                          <img src="assets/img/profiles/avatar-22.jpg" alt="Profile" class="rounded-circle">
                        </span>
                        <div class="flex-grow-1">
                          <p class="mb-1"><span class="text-dark fw-semibold">Brian Villaloboshas </span> cancelled the service scheduled for 14/01/2024.
                          </p>
                          <span>15 mins ago</span>
                        </div>
                      </div>
                    </a>
                  </div>
                </div>
              </div>
              <div class="d-flex p-0 notification-footer-btn">
                <a href="#" class="btn btn-light rounded  me-2">Cancel</a>
                <a href="#" class="btn btn-dark rounded ">View All</a>
              </div>
            </div>
          </div>
          <div class="provider-head-links">
            <a [routerLink]="routes.customerChat" class="d-flex align-items-center justify-content-center me-2"><i class="feather icon-mail"></i></a>
          </div>
          <div class="dropdown">
            <a href="javascript:void(0);" data-bs-toggle="dropdown" aria-expanded="false" class="">
              <div class="booking-user d-flex align-items-center">
                <span class="user-img">
                  <img src="assets/img/profiles/avatar-02.jpg" alt="user">
                </span>
              </div>
            </a>
            <ul class="dropdown-menu p-2">
              <li><a class="dropdown-item d-flex align-items-center" [routerLink]="routes.login"><i class="ti ti-logout me-1"></i>Logout</a></li>
            </ul>
          </div>
          <div class="header__hamburger d-lg-none my-auto">
            <div class="sidebar-menu">
              <i class="fa-solid fa-bars"></i>
            </div>
          </div>
        </div>
      }
    </nav>
  </div>
</header>
